stages:
  - deploy

image: registry.gitlab.arabyadscloud.com/arabyads/infrastructure:5

services:
- docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  IMAGE_URL: 501127779088.dkr.ecr.us-east-1.amazonaws.com/rate-card:$CI_COMMIT_SHA

deploy:
  stage: deploy
  before_script:
    - chmod +x /entrypoint.sh
    - sh /entrypoint.sh
  script:
    - docker build -f deployment/Dockerfile -t $IMAGE_URL .
    - docker push $IMAGE_URL
    - kubectl set image deployment/rate-card rate-card=$IMAGE_URL
